version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Test JavaScript
          command: yarn test
      - run:
          name: Report coverage
          command: bash <(curl -s https://codecov.io/bash)
